eureka:
  client:
    service-url:
      #与服务端地址一样，将客服端注册到服务端
      defaultZone: http://47.110.47.45:1006/eureka/,http://47.110.47.45:1007/eureka/
  instance:
    #自定义主机映射名称
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #表示将自己的IP注册到Eureka Server
    prefer-ip-address: true