version: "3"
services:
  nacos-server:
    container_name: nacos
    image: nacos/nacos-server:latest
    networks:
      - nacos_net
    volumes:
      - ../logs:/home/nacos/logs
      - ../init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ../env/nacos-ip.env
    restart: on-failure
networks:
  nacos_net:
    driver: bridge