spring:
  datasource:
    druid:
      #引入了p6spy模块后，需要指定db-type,不配置否则报错Caused by: java.lang.IllegalStateException: dbType not support : null, url jdbc:p6spy:mysql://localhost:3306/eshop_member?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      db-type: mysql
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
#      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall,config
#      min-evictable-idle-time-millis: 300000
#      pool-prepared-statements: true
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      validation-query: SELECT 1
#      validation-query-timeout: 1000
#      stat-view-servlet:
#        enabled: true
#        login-username: 'admin'
#        login-password: 'admin'
#        reset-enable: true
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/* '
#      filter:
#        stat:
#          db-type: mysql
#        wall:
#          db-type: mysql

mybatis-plus:
  #  global-config:
  #    db-config:
  #      #主键类型：AUTO（数据库ID自增），NONE（），INPUT（用户输入ID），ID_WORKER（全局唯一ID (数字类型)）, UUID（全局唯一ID UUID），ID_WORKER_STR（全局唯一ID (字符类型)）
  #      id-type: AUTO
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    # 开启驼峰命名匹配
#    map-underscore-to-camel-case: true
#    # 开启懒加载
#    lazyLoadingEnabled: true
#    aggressiveLazyLoading: false
#    # 开启缓存
#    cache-enabled: false
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'
uid:
  timeBits: 37
  workerBits: 17
  seqBits: 9