spring:
  datasource:
    druid:
      #引入了p6spy模块后，需要指定db-type,不配置否则报错Caused by: java.lang.IllegalStateException: dbType not support : null, url jdbc:p6spy:mysql://localhost:3306/eshop_member?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      db-type: mysql
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
#      driver-class-name: com.mysql.jdbc.Driver
#      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall,config
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-username: 'admin'
        login-password: 'admin'
        reset-enable: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      validation-query-timeout: 1000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/* '
