server:
  port: 6001

eureka:
  client:
    service-url:
      #与服务端地址一样，将客服端注册到服务端
      defaultZone: http://localhost:2001/eureka/,http://localhost:2002/eureka/
  instance:
    #自定义主机映射名称
    instance-id: ${spring.application.name}-${server.port}
    #表示将自己的IP注册到Eureka Server
    prefer-ip-address: true