server:
  port: 1001

eureka:
  client:
    service-url:
      #与服务端地址一样，将客服端注册到服务端
      defaultZone: http://eureka2001.com:2001/eureka/,http://eureka2002.com:2002/eureka/
  instance:
    #自定义主机映射名称
    instance-id: ${spring.application.name}-${server.port}
    #表示将自己的IP注册到Eureka Server
    prefer-ip-address: true

# 打印Config Server请求Git仓库的细节
#logging:
#  level:
#    org.springframework.cloud: DEBUG
#    org.springframework.boot: DEBUG

#开启Actuator所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

